export const errors = {
  // Auth
  ERR_UNAUTHORIZED: "ERR_UNAUTHORIZED",
  ERR_FORBIDDEN: "ERR_FORBIDDEN",
  ERR_INVALID_AUTH: "ERR_INVALID_AUTH",
  // Login
  ERR_LOGIN_INVALID_USER: "ERR_LOGIN_INVALID_USER",
  ERR_LOGIN_INVALID_PASSWORD: "ERR_LOGIN_INVALID_PASSWORD",
  // Signup
  ERR_SIGNUP_USER_EXISTS: "ERR_SIGNUP_USER_EXISTS",
  ERR_SIGNUP_INVALID_PASSWORD: "ERR_SIGNUP_INVALID_PASSWORD",
  ERR_SIGNUP_INVALID_USERNAME: "ERR_SIGNUP_INVALID_USERNAME",
  ERR_SIGNUP_USER_CREATE_ERROR: "ERR_SIGNUP_USER_CREATE_ERROR",
};
